name: Helm Github Action
description: Setup Helm and plugins, update repositories and applies configuration
author: hiberbee
branding:
  icon: anchor
  color: blue
inputs:
  helm-version:
    default: 3.3.0
    description: Helm version
    required: false
  helmfile-version:
    default: 0.125.5
    description: Helmfile version
    required: false
  repository-config:
    default: repositories.yaml
    description: Path to the file containing Helm repository names and URLs
    required: false
  helm-command:
    default: ''
    description: Helm command arguments
    required: false
  helmfile-command:
    default: ''
    description: Helmfile command arguments
    required: false
  helmfile-file:
    default: helmfile.yaml
    description: Load config from file or directory.
    required: false
outputs: {}
runs:
  using: node12
  main: dist/index.js
