name: CI
on:
  push:
    paths:
      - src/**
      - .github/workflows/**
      - action.yml
jobs:
  helm:
    name: Helm
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@main

      - name: Get repositories
        uses: hiberbee/github-action-helm@latest
        with:
          helm-command: repo list
          repository-config: test/repositories.yaml

      - name: Lint chart
        run: helm lint nginx
        working-directory: test/charts

      - name: Install release
        uses: hiberbee/github-action-helm@latest
        with:
          helm-command: upgrade --install --dry-run nginx test/charts/nginx

  helmfile:
    name: Helmfile
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@main

      - name: Setup K8s cluster
        uses: hiberbee/github-action-minikube@latest

      - name: Apply Helmfile
        uses: hiberbee/github-action-helm@latest
        with:
          helmfile-command: apply
          helmfile-config: test/helmfile.yaml

      - name: Get ingresses
        run: kubectl get ingress
